### ISSUE TITLE
alpha release checklist

### ISSUE THREAD

**Issue by ungoldman** [Esri/geotrigger-editor#73]
requirements:
- [x] update method
- [x] correct form contents & serialization
- [x] loading & error views / notifications
- [x] resize map width
  - to fix zoom issues and make notifications easier to position also
- [x] click on shape to edit
- [x] implement search & simplify style for basic theme

behavioral changes:
- [x] center without zoom on shape create/edit
- [x] add clear button to clear form & shape

outstanding issues:
- [x] cancel editing mode on drawer close

enhancements:
- [x] implement routing
- [x] move core state logic (& view management) to controller
